import exceptions_2_2

print(exceptions_2_2.greet('Kirr'))
